name: BetterSleeping4
author: vallas
version: ${project.version}
api-version: "1.13"
main: be.betterplugins.bettersleeping.BetterSleeping
description: A plugin that makes sleeping in multiplayer fun again!
softdepend: [Essentials, PlaceholderAPI, MultiWorld, Multiverse, Multiverse-Core, BentoBox, Skyblock, GSit]
commands:
    bettersleeping:
        description: See all BetterSleeping commands
        usage: Perform /bettersleeping help or /bs help to see a list of commands
        default: true
        aliases: [bs, bs4]
permissions:
    bettersleeping.*:
        description: Gives access to all BetterSleeping commands
        children:
            bettersleeping.help: true
            bettersleeping.reload: true
            bettersleeping.status: true
            bettersleeping.buffs: true
            bettersleeping.help.admin: true
            bettersleeping.version: true
            bettersleeping.shout: true
            bettersleeping.sleepcommand: true
            bettersleeping.bypass: false
    bettersleeping.user:
        description: Collection of commands that default users may want access to
        children:
            bettersleeping.reload: false
            bettersleeping.status: true
            bettersleeping.help: true
            bettersleeping.help.admin: false
            bettersleeping.buffs: true
            bettersleeping.version: false
            bettersleeping.shout: true
            bettersleeping.sleepcommand: false
            bettersleeping.bypass: false
    bettersleeping.admin:
        description: Collection of commands that admins may want access to (all permissions except bypass)
        children:
            bettersleeping.reload: true
            bettersleeping.status: true
            bettersleeping.help: true
            bettersleeping.help.admin: true
            bettersleeping.buffs: true
            bettersleeping.version: true
            bettersleeping.shout: true
            bettersleeping.sleepcommand: false
            bettersleeping.bypass: false
    bettersleeping.reload:
        description: Gives access to /bs reload, which will reload the BetterSleeping config files
        default: op
    bettersleeping.status:
        description: Gives access to /bs status or /bs s, which will display info about the sleeping players
        default: true
    bettersleeping.bypass:
        description: This player will be ignored from the required player count, but will be able to sleep and get buffs (never debuffs)
        default: false
    bettersleeping.sleepcommand:
        description: Gives acces to /bs sleep, which will make the plugin think that the player is sleeping
        default: op
    bettersleeping.help.admin:
        description: Gives access to /bs help, which will give info about all commands the user has access to and permission nodes will be shown as well
        default: op
    bettersleeping.help:
        description: Gives access to /bs help, which will give info about all commands a user has access to
        default: true
    bettersleeping.version:
        description: Gives access to /bs version, which will show the version of BetterSleeping
        default: op
    bettersleeping.buffs:
        description: Gives access to /bs buffs, which will show the (de)buffs this user will receive
        default: true
    bettersleeping.shout:
        description: Gives access to /bs shout, which will request all players in that world to sleep. Has a per-world cooldown.
        default: true