name: BetterSleeping3
author: vallas
version: 3.0.0
api-version: "1.13"
main: be.dezijwegel.bettersleeping.BetterSleeping
description: A plugin that makes sleeping in multiplayer fun again!
softdepend: [Essentials, PlaceholderAPI]
commands:
    bettersleeping:
        description: See all BetterSleeping commands
        usage: Perform /bettersleeping help or /bs help to see a list of commands!
        default: true
        aliases: [bs]
permissions:
    bettersleeping.*:
        description: Gives access to all BetterSleeping commands (/bs skip not included so you may want to add acces through bettersleeping.bypass)
        children:
            bettersleeping.help: true
            bettersleeping.reload: true
            bettersleeping.status: true
            bettersleeping.buffs: true
            bettersleeping.help.admin: true
            bettersleeping.version: true
    bettersleeping.user:
        description: Collection of commands that default users may want access to
        children:
            bettersleeping.reload: false
            bettersleeping.status: true
            bettersleeping.help: true
            bettersleeping.help.admin: false
            bettersleeping.buffs: true
            bettersleeping.version: false
    bettersleeping.admin:
        description: Collection of commands that admins may want access to (all permissions except bypass)
        children:
            bettersleeping.reload: true
            bettersleeping.status: true
            bettersleeping.help: true
            bettersleeping.help.admin: true
            bettersleeping.buffs: true
            bettersleeping.version: true
    bettersleeping.reload:
        description: Gives access to /bs reload, which will reload the BetterSleeping config files
        default: op
    bettersleeping.status:
        description: Gives access to /bs status or /bs s, which will display info about the sleeping players
        default: true
    bettersleeping.bypass:
        description: This player will be ignored from the required player count and will not be able to sleep
        default: false
    bettersleeping.help.admin:
        description: Gives access to /bs help, which will give info about all commands the user has access to and permission nodes will be shown as well
        default: op
    bettersleeping.help:
        description: Gives access to /bs help, which will give info about all commands a user has access to
        default: true
    bettersleeping.version:
        description: Gives access to /bs version, which will show the version of BetterSleeping
        default: op
    bettersleeping.buffs:
        description: Gives access to /bs buffs, which will show the (de)buffs this user will receive
        default: true